version: "2"
services:
    composer:
        image: composer/composer:php7
        container_name: captcha_composer
        command: update --lock --ignore-platform-reqs
        volumes:
            - ../app:/app
    nginx:
        image: phalconphp/nginx
        container_name: captcha_nginx
        ports:
            - "7000:80"
        volumes:
            - ../app:/app
            - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
            - ./nginx/default.conf:/etc/nginx/sites-enabled/default.conf
        depends_on:
            - php
    php:
        build:
            context: ./phalcon
            dockerfile: Dockerfile
        entrypoint: ""
        command: bash -c "php-fpm7.0 -F"
        container_name: captcha_phalcon
        working_dir: /app
#        ports:
#            - "12000:9000"
#            - "13000:9001"
        volumes:
            - ../app:/app
        depends_on:
            - redis
            - rabbitmq
            - composer
        links:
            - redis
            - rabbitmq
            - composer
        dns: 8.8.8.8
    pm2:
        build:
            context: ./pm2
            dockerfile: Dockerfile
        entrypoint: ""
        command: bash -c "pm2 start public/cli.php --interpreter=php && pm2 logs"
        working_dir: /app
        volumes:
            - ../app:/app
        depends_on:
            - php
        links:
            - php
        dns: 8.8.8.8
    redis:
        image: redis:alpine
        command: redis-server --requirepass redis
        container_name: captcha_redis
        volumes:
            - captcha-redis:/data
    rabbitmq:
        image: 'rabbitmq:3-management'
        hostname: captcha_rabbitmq_hn
        container_name: captcha_rabbitmq
        ports:
            - 9900:15672
        volumes:
            - captcha-rabbitmq:/var/lib/rabbitmq

volumes:
  captcha-redis:
  captcha-rabbitmq:
  captcha-mongo: